language: csharp
mono: none
dotnet: 1.0.1
dist: trusty

script:
  - cd CircuitDiagram
  - dotnet restore
  - dotnet test CircuitDiagram.Compiler.Test/CircuitDiagram.Compiler.Test.csproj
  - dotnet publish ComponentCompiler/ComponentCompiler.csproj -c Release -r win10-x64
